### PR TITLE
Support for type definition when using suspense

### PR DESCRIPTION
**Pull request by sskmy1024y**
| before | after |
|---|---|
| image | image |

trpc-swr is a great library, but there is one problem.
That is that type completion does not work properly when using suspense mode to retrieve data.

We have created a PR that fixes this issue. We hope it will be a better library!

### CODE REVIEW

**Comment by sannajammeh** [comment]
Apologies for the wait, Ill be looking at this tonight!

**Comment by sskmy1024y** [comment]
@sannajammeh Thank you. We are looking forward to your approve.

**Comment by sannajammeh** [comment]
@sskmy1024y Hey, nice work! PR works excellent. I added a test case for the suspense types. Could you give me push permissions to your fork?

**Comment by sskmy1024y** [comment]
@sannajammeh Thank you! You have been added to collaborator. Please check it out!

**Pull request merged**
